name: Build and Release C++ Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up C++ build environment
        uses: actions/setup-cpp@v1
        with:
          compiler: 'gcc'

      - name: Install dependencies (optional)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Create a release artifact
        run: |
          mkdir release
          cp build/my_binary release/

      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
