name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout des Repositories
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup von CMake und Build-Tools
      - name: Set up CMake
        uses: cmake/setup-cmake@v3

      # Setup von Build-Tools
      - name: Set up build tools
        run: sudo apt-get install -y build-essential

      # Erstellen eines Build-Verzeichnisses und Bauen des Projekts
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build


  release:
    runs-on: ubuntu-latest
    needs: build
    name: Release
    permissions: write-all
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: windows-build
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false
