name: C++ CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      question:
        description: "Start Build"
        required: false
        type: choise
        default: "yes"
        options:
          - "yes"
          - "no"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: cmake/setup-cmake@v3

      - name: Set up build tools
        run: sudo apt-get install -y build-essential

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build


  release:
    runs-on: ubuntu-latest
    needs: build
    name: Release
    permissions: write-all
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
          draft: false
          prerelease: false
